### ISSUE TITLE
Trouble to generate .pkg installer (README.md replacing)

### ISSUE THREAD

**Issue by xyNNN** [oclif/oclif#103]
Hey folks,

I've some trouble with generating a .pkg installer with the oclif-dev package. After executing the command `yarn run prepack` I get the following output:

```
❯ yarn run prepack
yarn run v0.27.5
$ rm -rf lib && tsc && oclif-dev manifest && oclif-dev readmeD
wrote manifest to /Users/xynnn/Projects/Oclif/test-cli/.oclif.manifest.json
replacing <!-- usage --> in README.md
TypeError: Cannot read property 'replace' of undefined
    at Readme.commandCode (~/Projects/Oclif/test-cli/node_modules/@oclif/dev-cli/lib/commands/readme.js:148:38)
    at Readme.renderCommand (~/Projects/Oclif/test-cli/node_modules/@oclif/dev-cli/lib/commands/readme.js:127:18)
    at commands.map.c (~/Projects/Oclif/test-cli/node_modules/@oclif/dev-cli/lib/commands/readme.js:108:39)
    at Array.map (<anonymous>)
    at Readme.commands (~/Projects/Oclif/test-cli/node_modules/@oclif/dev-cli/lib/commands/readme.js:108:25)
    at Readme.run (~/Projects/Oclif/test-cli/node_modules/@oclif/dev-cli/lib/commands/readme.js:36:112)
    at <anonymous>
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

My README.md have the necessary placeholders "toc", "usage", "commands". Anybody know to solve this issue?

Thanks in advance.

**Comment by jdxcode** [comment]
what is the 'repository' attribute set to? It's set to something that's causing it to fail I think

**Comment by jdxcode** [comment]
closing in favor of https://github.com/oclif/dev-cli/issues/24 which is the real issue
