### ISSUE TITLE
empty manifest

### ISSUE THREAD

**Issue by endquote** [oclif/oclif#1050]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
bug, but it's probably something I did

What is the current behavior?
-----------------------------
I'm finding that running `oclif manifest` in my project is generating an empty manifest, so commands don't run with `bin/run`, but they do with `bin/dev`.

What is the expected behavior?
------------------------------
The manifest should have the command info, as it has in my other oclif projects.

Here is the repo: https://github.com/endquote/mastodon-utils

**Comment by mattwebbio** [comment]
Shot in the dark here, but did you try running `pnpm run build` first? IIRC, `bin/run` runs your compiled output in the `dist` directory

**Comment by endquote** [comment]
I think both `bin/run` and `bin/dev` look at `oclif.manifest.json` for commands.

If I run the `prepack` script, which is `pnpm build && oclif manifest && oclif readme`, I get a manifest like this:

`{"version":"0.0.1","commands":{}}`

With that manifest in place, no commands run. If I delete it, they run again.

```
❯ pnpm prepack

> mastodon-utils@0.0.1 prepack /Users/endquote/Source/mastodon-feedbin
> pnpm build && oclif manifest && oclif readme

> mastodon-utils@0.0.1 build /Users/endquote/Source/mastodon-feedbin
> shx rm -rf dist && tsc -b

wrote manifest to /Users/endquote/Source/mastodon-feedbin/oclif.manifest.json
replacing <!-- usage --> in README.md
replacing <!-- commands --> in README.md
replacing <!-- toc --> in README.md

❯ cat oclif.manifest.json
{"version":"0.0.1","commands":{}}%                                                                                                                                        

❯ ./bin/run sync-stars
 ›   Error: command sync-stars not found

❯ ./bin/dev sync-stars
Error: command sync-stars not found
    at Config.runCommand (/Users/endquote/Source/mastodon-feedbin/node_modules/.pnpm/@oclif+core@1.19.1/node_modules/@oclif/core/lib/config/config.js:268:19)
    at async Object.run (/Users/endquote/Source/mastodon-feedbin/node_modules/.pnpm/@oclif+core@1.19.1/node_modules/@oclif/core/lib/main.js:76:5)

❯ rm oclif.manifest.json 

❯ ./bin/run sync-stars
 ›   Error: command sync-stars not found

❯ ./bin/dev sync-stars
[command runs]
```

I tried switching back to `yarn` but that didn't help.

**Comment by endquote** [comment]
I think the issue is with the build command not actually building when run with `yarn build` or `pnpm build`.

```
# note no dist folder
❯ ls            
LICENSE                 declarations.d.ts       pnpm-lock.yaml          tmp
README.md               node_modules            src                     tsconfig.json
bin                     package.json            test                    tsconfig.tsbuildinfo

❯ pnpm run build

> mastodon-utils@0.0.1 build /Users/endquote/Source/mastodon-feedbin
> shx rm -rf dist && tsc -b


# still no dist folder
❯ ls
LICENSE                 declarations.d.ts       pnpm-lock.yaml          tmp
README.md               node_modules            src                     tsconfig.json
bin                     package.json            test                    tsconfig.tsbuildinfo

❯ yarn run build
yarn run v1.22.19
$ shx rm -rf dist && tsc -b
✨  Done in 0.54s.

# still no dist folder
❯ ls
LICENSE                 declarations.d.ts       pnpm-lock.yaml          tmp
README.md               node_modules            src                     tsconfig.json
bin                     package.json            test                    tsconfig.tsbuildinfo

❯ node ./node_modules/shx/lib/cli.js rm -rf dist && tsc -b

# no there is a dist folder
❯ ls
LICENSE                 dist                    src                     tsconfig.tsbuildinfo
README.md               node_modules            test
bin                     package.json            tmp
declarations.d.ts       pnpm-lock.yaml          tsconfig.json
```

If I run `oclif` manifest when `dist` exists, the manifest comes out fine. If `dist` does not exist, the manifest is empty, which makes sense.
