### ISSUE TITLE
cryptic "command not found" returned on typercript transpile error

### ISSUE THREAD

**Issue by martin-mindflow** [oclif/oclif#1141]
What is the current behavior?
-----------------------------
I have an ocilf cli written as an ES Module in TypeScript inside of an nx monorepo. When a command has a TS error (like an invalid type conversion), i get this error message: 

```
> nx run cli migrate some-args

 ›   Error: command migrate not found
```

Without any additional details. I have to run manually `node (...options) path/to/oclif/cli/commands/migrate` in order to get details on the error. It seems like oclif is somehow catching it tho as running in verbose (with `DEBUG=*`) yields:

```
> nx run cli some-args

2023-04-19T07:46:22.492Z config reading core plugin /path/to/cli
2023-04-19T07:46:22.492Z config loadJSON /path/to/cli/package.json
2023-04-19T07:46:22.493Z config loadJSON /path/to/cli/oclif.manifest.json
2023-04-19T07:46:22.493Z config loadJSON /path/to/cli/.oclif.manifest.json
2023-04-19T07:46:22.514Z config:@myorg/cli-package loading IDs from /path/to/cli/src/lib/commands
2023-04-19T07:46:22.518Z config:@myorg/cli-package found commands [
  # ... the full list of other commands
  'migrate',
  # ... even more commands
]
TSError Plugin: @myorg/cli-package: ⨯ Unable to compile TypeScript:
path/to/ts/file/with/error.ts(183,78): error TS2339: Property 'xxxx' does not exist on type 'yyyyy'.
  Property 'xxx' does not exist on type 'yyyy'.
    at createTSError (/path/to/repo/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/path/to/repo/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/path/to/repo/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/path/to/repo/node_modules/ts-node/src/index.ts:1433:41)
    at transformSource (/path/to/repo/node_modules/ts-node/src/esm.ts:400:37)
    at /path/to/repo/node_modules/ts-node/src/esm.ts:278:53
    at async addShortCircuitFlag (/path/to/repo/node_modules/ts-node/src/esm.ts:409:15)
    at async nextLoad (node:internal/modules/esm/loader:163:22)
    at async ESMLoader.load (node:internal/modules/esm/loader:605:20)
    at async ESMLoader.moduleProvider (node:internal/modules/esm/loader:457:11)
module: @oclif/core@1.26.2
task: toCached
plugin: @myorg/cli-package
root: /path/to/cli
See more details with DEBUG=*
TSError Plugin: @myorg/cli-package: ⨯ Unable to compile TypeScript:
path/to/ts/file/with/error.ts(183,78): error TS2339: Property 'xxxx' does not exist on type 'yyyyy'.
  Property 'xxx' does not exist on type 'yyyy'.
    at createTSError (/path/to/repo/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/path/to/repo/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/path/to/repo/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/path/to/repo/node_modules/ts-node/src/index.ts:1433:41)
    at transformSource (/path/to/repo/node_modules/ts-node/src/esm.ts:400:37)
    at /path/to/repo/node_modules/ts-node/src/esm.ts:278:53
    at async addShortCircuitFlag (/path/to/repo/node_modules/ts-node/src/esm.ts:409:15)
    at async nextLoad (node:internal/modules/esm/loader:163:22)
    at async ESMLoader.load (node:internal/modules/esm/loader:605:20)
    at async ESMLoader.moduleProvider (node:internal/modules/esm/loader:457:11)
module: @oclif/core@1.26.2
task: toCached
plugin: @myorg/cli-package
root: /path/to/cli
See more details with DEBUG=*
ExperimentalWarning: Importing JSON modules is an experimental feature. This feature could change at any time
    at emitExperimentalWarning (node:internal/util:227:11)
    at ESMLoader.jsonStrategy (node:internal/modules/esm/translators:267:3)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:468:14)
ExperimentalWarning: Importing JSON modules is an experimental feature. This feature could change at any time
    at emitExperimentalWarning (node:internal/util:227:11)
    at ESMLoader.jsonStrategy (node:internal/modules/esm/translators:267:3)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:468:14)
2023-04-19T07:46:25.667Z config:@myorg/cli-package (import) /path/to/cli/src/lib/commands/command1.ts
2023-04-19T07:46:25.667Z config:@myorg/cli-package (import) /path/to/cli/src/lib/commands/command2.ts
2023-04-19T07:46:25.667Z config:@myorg/cli-package (import) /path/to/cli/src/lib/commands/command3.ts
#### .... other lines with the rest of the commands, but notably no lines for the migrate command
2023-04-19T07:46:25.802Z config reading user plugins pjson /Users/martinsteffen/.local/share/@myorg/cli-package/package.json
2023-04-19T07:46:25.802Z config loadJSON /Users/martinsteffen/.local/share/@myorg/cli-package/package.json
2023-04-19T07:46:25.805Z config loading plugins [ '@oclif/plugin-help' ]
2023-04-19T07:46:25.806Z config reading core plugin /path/to/repo/node_modules/@oclif/plugin-help
2023-04-19T07:46:25.806Z config loadJSON /path/to/repo/node_modules/@oclif/plugin-help/package.json
2023-04-19T07:46:25.807Z config loadJSON /path/to/repo/node_modules/@oclif/plugin-help/oclif.manifest.json
2023-04-19T07:46:25.807Z config:@oclif/plugin-help using manifest from /path/to/repo/node_modules/@oclif/plugin-help/oclif.manifest.json
2023-04-19T07:46:25.807Z config config done
2023-04-19T07:46:25.807Z config start init hook
2023-04-19T07:46:25.807Z config init hook done
2023-04-19T07:46:25.808Z config runCommand migrate some-args
2023-04-19T07:46:25.808Z config start command_not_found hook
2023-04-19T07:46:25.808Z config command_not_found hook done
 ›   Error: command migrate not found
```

What is the expected behavior?
------------------------------
I'm expecting the ts error to be shown so that debugging is possible without a trick

```
> nx run cli migrate some-args

 ›   Error: command migrate not found
```

oclif versions:
```
    "@oclif/core": "^2.8.2",
    "@oclif/plugin-help": "^5.2.9",
```

Thanks a lot :)

**Comment by mdonnalley** [comment]
This should be fixed in the latest major version of @oclif/core
