### ISSUE TITLE
How to use pkg with oclif (typescript)?

### ISSUE THREAD

**Issue by max-block** [oclif/oclif#134]
I'm trying to package my single cli project via pkg.
Your FAQs says:

> Use pkg. Just make sure to add the commands and other source files by setting pkg.scripts: "./lib/**/*.js" in package.json.

So, I've added to package.json:
```
"pkg": {
    "scripts": "./lib/**/*.js"
  }
```
But it doesn't work:

```
$ npm run prepare
$  pkg -t macos .
> pkg@4.3.3
> Warning Cannot resolve '`../${ dev ? 'src' : 'lib' }`'
  /Users/max7z/projects/test/t9/bin/run
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
$ ./t9
Error: Cannot find module 'typescript'
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:592:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1278:46)
    at Function.Module._load (internal/modules/cjs/loader.js:518:25)
    at Module.require (internal/modules/cjs/loader.js:648:17)
    at Module.require (pkg/prelude/bootstrap.js:1157:31)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.register (/snapshot/t9__demo__oclif_and_pkg/node_modules/ts-node/src/index.ts:227:26)
    at Object.<anonymous> (/snapshot/t9__demo__oclif_and_pkg/node_modules/ts-node/register/index.js:1:16)
    at Module._compile (pkg/prelude/bootstrap.js:1252:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)
```

I use typescript and it looks like pkg doesn't know how to work with ts-node/register.

P.S. Thank you for this amazing tool. It's so pleasant to make command line tools with it.

**Comment by oriqoqo** [comment]
Definitely an existing issue with typescript and yarn workspaces.

**Comment by Jarmos-san** [comment]
So, no one has figured out a way to make it work yet? 😞

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
