### ISSUE TITLE
Working with file-system-cache

### ISSUE THREAD

**Issue by jondewoo** [oclif/oclif#1490]
**Describe the bug**
Importing and using [file-system-cache](https://github.com/philcockfield/file-system-cache) (written in TypeScript, built for ESM with tsup) produces unrecoverable errors in CJS and ESM contexts alike.

**To Reproduce**

1. Clone either repro project: https://github.com/jondewoo/oclif-vs-file-system-cache-cjs or https://github.com/jondewoo/oclif-vs-file-system-cache-esm
2. Install dependencies: `npm i`
3. Run a simple command: `./bin/dev.js hello test --from=me`
4. See error:

In ESM context:
```
Warning: Error
    at Plugin.warn (/Users/jonathan/Documents/oclif-vs-file-system-cache-esm/node_modules/@oclif/core/lib/config/plugin.js:370:17)
    at /Users/jonathan/Documents/oclif-vs-file-system-cache-esm/node_modules/@oclif/core/lib/config/plugin.js:272:30
    at async Promise.all (index 0)
    at async Plugin._manifest (/Users/jonathan/Documents/oclif-vs-file-system-cache-esm/node_modules/@oclif/core/lib/config/plugin.js:253:24)
    at async Plugin.load (/Users/jonathan/Documents/oclif-vs-file-system-cache-esm/node_modules/@oclif/core/lib/config/plugin.js:204:25)
    at async PluginLoader.loadRoot (/Users/jonathan/Documents/oclif-vs-file-system-cache-esm/node_modules/@oclif/core/lib/config/plugin-loader.js:43:13)
    at async Config.load (/Users/jonathan/Documents/oclif-vs-file-system-cache-esm/node_modules/@oclif/core/lib/config/config.js:280:27)
    at async Function.load (/Users/jonathan/Documents/oclif-vs-file-system-cache-esm/node_modules/@oclif/core/lib/config/config.js:167:9)
    at async run (/Users/jonathan/Documents/oclif-vs-file-system-cache-esm/node_modules/@oclif/core/lib/main.js:62:20)
    at async file:///Users/jonathan/Documents/oclif-vs-file-system-cache-esm/bin/dev.js:6:1
module: @oclif/core@4.0.13
task: findCommand (hello)
plugin: oclif-vs-file-system-cache-esm
root: /Users/jonathan/Documents/oclif-vs-file-system-cache-esm
message: Dynamic require of "fs" is not supported
See more details with DEBUG=*
Error: command hello:test not found
    at Config.runCommand (/Users/jonathan/Documents/oclif-vs-file-system-cache-esm/node_modules/@oclif/core/lib/config/config.js:394:19)
    at async run (/Users/jonathan/Documents/oclif-vs-file-system-cache-esm/node_modules/@oclif/core/lib/main.js:95:16)
    at async file:///Users/jonathan/Documents/oclif-vs-file-system-cache-esm/bin/dev.js:6:1
```

In CJS context:
```
(node:46503) [ERR_PACKAGE_PATH_NOT_EXPORTED] Warning: Error
module: @oclif/core@4.0.13
task: findCommand (hello)
plugin: oclif-vs-file-system-cache-cjs
root: /Users/jonathan/Documents/oclif-vs-file-system-cache-cjs
code: ERR_PACKAGE_PATH_NOT_EXPORTED
message: No "exports" main defined in /Users/jonathan/Documents/oclif-vs-file-system-cache-cjs/node_modules/file-system-cache/package.json
See more details with DEBUG=*
(Use `node --trace-warnings ...` to show where the warning was created)
Warning: Error
    at Plugin.warn (/Users/jonathan/Documents/oclif-vs-file-system-cache-cjs/node_modules/@oclif/core/lib/config/plugin.js:370:17)
    at /Users/jonathan/Documents/oclif-vs-file-system-cache-cjs/node_modules/@oclif/core/lib/config/plugin.js:272:30
    at async Promise.all (index 0)
    at async Plugin._manifest (/Users/jonathan/Documents/oclif-vs-file-system-cache-cjs/node_modules/@oclif/core/lib/config/plugin.js:253:24)
    at async Plugin.load (/Users/jonathan/Documents/oclif-vs-file-system-cache-cjs/node_modules/@oclif/core/lib/config/plugin.js:204:25)
    at async PluginLoader.loadRoot (/Users/jonathan/Documents/oclif-vs-file-system-cache-cjs/node_modules/@oclif/core/lib/config/plugin-loader.js:43:13)
    at async Config.load (/Users/jonathan/Documents/oclif-vs-file-system-cache-cjs/node_modules/@oclif/core/lib/config/config.js:280:27)
    at async Function.load (/Users/jonathan/Documents/oclif-vs-file-system-cache-cjs/node_modules/@oclif/core/lib/config/config.js:167:9)
    at async run (/Users/jonathan/Documents/oclif-vs-file-system-cache-cjs/node_modules/@oclif/core/lib/main.js:62:20)
    at async /Users/jonathan/Documents/oclif-vs-file-system-cache-cjs/bin/dev.js:5:3
module: @oclif/core@4.0.13
task: findCommand (hello)
plugin: oclif-vs-file-system-cache-cjs
root: /Users/jonathan/Documents/oclif-vs-file-system-cache-cjs
code: ERR_PACKAGE_PATH_NOT_EXPORTED
message: No "exports" main defined in /Users/jonathan/Documents/oclif-vs-file-system-cache-cjs/node_modules/file-system-cache/package.json
See more details with DEBUG=*
Error: command hello:test not found
    at Config.runCommand (/Users/jonathan/Documents/oclif-vs-file-system-cache-cjs/node_modules/@oclif/core/lib/config/config.js:394:19)
    at async run (/Users/jonathan/Documents/oclif-vs-file-system-cache-cjs/node_modules/@oclif/core/lib/main.js:95:16)
    at async /Users/jonathan/Documents/oclif-vs-file-system-cache-cjs/bin/dev.js:5:3
```

**Expected behavior**
There should not be errors.

**Your Environment (please complete the following information):**

- `oclif` Version 4.14.8
- OS & version: macOS Sonoma 14.5
- Shell/terminal & version: zsh 5.9 (x86_64-apple-darwin23.0)

**Comment by mdonnalley** [comment]
@jondewoo Thanks for the issue and the repos! I'm going to close this because I suspect that this is an issue with the latest major of file-system-cache. I have two reasons:

1. Downgrading to 2.4.7 worked for both the ESM and CJS repos you provided
2. If you `npm init` a new project and add file-system-cache, you'll see the same error:

```js
// index.js
import { Cache } from 'file-system-cache';
```

```
❯ node index.js

Error: Dynamic require of "fs" is not supported
    at file:///Users/mdonnalley/code/file-system-cache-bug/node_modules/file-system-cache/lib/index.js:6:382
    at file:///Users/mdonnalley/code/file-system-cache-bug/node_modules/file-system-cache/lib/index.js:6:7064
    at file:///Users/mdonnalley/code/file-system-cache-bug/node_modules/file-system-cache/lib/index.js:6:458
    at file:///Users/mdonnalley/code/file-system-cache-bug/node_modules/file-system-cache/lib/index.js:7:4622
    at file:///Users/mdonnalley/code/file-system-cache-bug/node_modules/file-system-cache/lib/index.js:6:458
    at file:///Users/mdonnalley/code/file-system-cache-bug/node_modules/file-system-cache/lib/index.js:7:9971
    at file:///Users/mdonnalley/code/file-system-cache-bug/node_modules/file-system-cache/lib/index.js:6:458
    at file:///Users/mdonnalley/code/file-system-cache-bug/node_modules/file-system-cache/lib/index.js:11:2149
    at file:///Users/mdonnalley/code/file-system-cache-bug/node_modules/file-system-cache/lib/index.js:6:458
    at file:///Users/mdonnalley/code/file-system-cache-bug/node_modules/file-system-cache/lib/index.js:12:3721

Node.js v20.13.1
```
