### ISSUE TITLE
Generated CLI with Typescript options fails at runtime

### ISSUE THREAD

**Issue by heyMP** [oclif/oclif#170]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Bug

What is the current behavior?
-----------------------------
Creating a new cli using the oclif generator with the Typescript options.  Publish the package to npm.  Install package globally.  Executing the cli throws a `Cannot find module` error.

Example:

```
Error: Cannot find module '/usr/local/lib/node_modules/heymptestcli/lib/commands/wutup'
    at fetch (/usr/local/lib/node_modules/heymptestcli/node_modules/@oclif/config/lib/plugin.js:96:31)
    at Plugin.findCommand (/usr/local/lib/node_modules/heymptestcli/node_modules/@oclif/config/lib/plugin.js:114:21)
    at Object.load (/usr/local/lib/node_modules/heymptestcli/node_modules/@oclif/config/lib/plugin.js:47:72)
    at Config.runCommand (/usr/local/lib/node_modules/heymptestcli/node_modules/@oclif/config/lib/config.js:149:27)
    at Main.run (/usr/local/lib/node_modules/heymptestcli/node_modules/@oclif/command/lib/main.js:21:27)
    at Main._run (/usr/local/lib/node_modules/heymptestcli/node_modules/@oclif/command/lib/command.js:29:31)
    at <anonymous>
```

Steps to reproduce
------------------------------
I recorded a video of steps to reproduce https://www.youtube.com/watch?v=qp6BN8KDNiU&feature=youtu.be
```
$ npx oclif multi mycli # answer yes to typescript options
$ cd mycli
$ npm publish # publish to npm
$ npm install -g mycli # install new package globally
$ mycli # run the cli
```

Debug my example cli
------------------------------
```
$ docker run --rm -it node:8 bash # from local machine
$ npm install -g heymptestcli # from inside container
$ heymptestcli hello # this should throw error
```

Environments
------------------------------
Please mention your oclif and OS version.
Tested on OSX 10.13 and docker node:8 image

Notes
------------------------------
We are running into the same error on our wcfactory cli: https://www.npmjs.com/package/@wcfactory/cli

I assume it's related to the typescript runtime?

**Comment by nivrith009** [comment]
I think, the binary is looking for the compiled js output in lib directory which doesn't exists 

It worked for me by adding `rm -rf lib && tsc` to srcipts.prepack in package.json

i.e. I changed the original package.json 

from 
`"scripts": {
"prepack": "oclif-dev manifest && oclif-dev readme && npm shrinkwrap", ...
}
`

to 


`"scripts": {
"prepack": "rm -rf lib && tsc && oclif-dev manifest && oclif-dev readme && npm shrinkwrap", ...
}
`

**Comment by nitaking** [comment]
@nivrith
I think this is happening now. Is this wrong?
```
$ npx oclif -v
oclif/1.13.2 darwin-x64 node-v9.11.2

```

**Comment by nitaking** [comment]
```
yarn global add gitmoji-c

 $ gitmoji
gitmoji-c is a gitmoji-cli clone tool that does not use gpg.

VERSION
  gitmoji-c/0.0.3 darwin-x64 node-v9.11.2

USAGE
  $ gitmoji [COMMAND]

COMMANDS
  commit  Interactively commit using the prompts
  help    display help for gitmoji
  list    List all the available gitmojis

 $ gitmoji list
Error: Cannot find module '/Users/user2/.config/yarn/global/node_modules/gitmoji-c/lib/commands/list'
    at fetch (~/.config/yarn/global/node_modules/@oclif/config/lib/plugin.js:97:31)
    at Plugin.findCommand (~/.config/yarn/global/node_modules/@oclif/config/lib/plugin.js:115:21)
    at Object.load (~/.config/yarn/global/node_modules/@oclif/config/lib/plugin.js:48:72)
    at Config.runCommand (~/.config/yarn/global/node_modules/@oclif/config/lib/config.js:149:27)
    at Main.run (~/.config/yarn/global/node_modules/@oclif/command/lib/main.js:21:27)
    at Main._run (~/.config/yarn/global/node_modules/@oclif/command/lib/command.js:44:31)
    at <anonymous>

```

https://github.com/nitaking/gitmoji-c
https://www.npmjs.com/package/gitmoji-c
