### ISSUE TITLE
Help does not work

### ISSUE THREAD

**Issue by venkyvb** [oclif/oclif#187]
I have generate a simple Single command CLI

```
// index.js file

const {Command, flags} = require('@oclif/command')

class TokenTestCommand extends Command {
  async run() {
    const {flags} = this.parse(TokenTestCommand)
    const name = flags.name || 'world'
    this.log(`hello ${name} from ./src/index.js`)
  }
}

TokenTestCommand.description = `Describe the command here
...
Extra documentation goes here
`

TokenTestCommand.flags = {
  // add --version flag to show CLI version
  version: flags.version({char: 'v'}),
  // add --help flag to show CLI version
  help: flags.help({char: 'h'}),
  name: flags.string({char: 'n', description: 'name to print'}),
}

module.exports = TokenTestCommand

```
When I run ```./bin/run --help```

```
➜  token_test ./bin/run --help
TypeError: Cannot read property 'split' of undefined
    at Help.showCommandHelp (~/token_test/node_modules/@oclif/plugin-help/lib/index.js:70:28)
    at TokenTestCommand._help (~/token_test/node_modules/@oclif/command/lib/command.js:103:14)
    at TokenTestCommand.init (~/token_test/node_modules/@oclif/command/lib/command.js:63:25)
    at TokenTestCommand._run (~/token_test/node_modules/@oclif/command/lib/command.js:28:24)
    at Function.Command.run (~/token_test/node_modules/@oclif/command/lib/command.js:133:16)
    at <anonymous>
➜  token_test ./bin/run -h
TypeError: Cannot read property 'split' of undefined
    at Help.showCommandHelp (~/token_test/node_modules/@oclif/plugin-help/lib/index.js:70:28)
    at TokenTestCommand._help (~/token_test/node_modules/@oclif/command/lib/command.js:103:14)
    at Object.parse (~/token_test/node_modules/@oclif/command/lib/flags.js:37:17)
    at Parser._flags (~/token_test/node_modules/@oclif/parser/lib/parse.js:142:42)
    at Parser.parse (~/token_test/node_modules/@oclif/parser/lib/parse.js:112:28)
    at Object.parse (~/token_test/node_modules/@oclif/parser/lib/index.js:25:27)
    at TokenTestCommand.parse (~/token_test/node_modules/@oclif/command/lib/command.js:68:41)
    at TokenTestCommand.run (~/token_test/src/index.js:5:26)
    at TokenTestCommand._run (~/token_test/node_modules/@oclif/command/lib/command.js:29:31)
    at <anonymous>
➜  token_test
```
My node version is 8.12.0

**Comment by jdxcode** [comment]
try updating all the packages

**Comment by venkyvb** [comment]
@jdxcode Did the following:

```
rm -rf node_modules && npm update --save-dev && npm update --save
```
Unfortunately, this still doesn't seem to solve the issue.

**Comment by jdxcode** [comment]
looks like I didn't push a release for https://github.com/oclif/command/commit/46456dd962895f67616c16093c49cf91a571c5bc

If you update to the latest @oclif/command it should work now

**Comment by venkyvb** [comment]
Perfect. After update the modules now this works !!
