### ISSUE TITLE
Create Multi Command Fails in fast-glob

### ISSUE THREAD

**Issue by paulrenenichols** [oclif/oclif#200]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
**Bug**

What is the current behavior?
-----------------------------

Attempting to create a multi command using `npx oclif multi aws-pinpoint`

Seems to fail in **fast-glob**, and the command directory is created but is empty.

```
➜  aws-utilities npx oclif multi aws-pinpoint        
npx: installed 441 in 4.607s

     _-----_     ╭──────────────────────────╮
    |       |    │      Time to build a     │
    |--(o)--|    │  multi-command CLI with  │
   `---------´   │  oclif! Version: 1.12.8  │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

? npm package name aws-pinpoint
? command bin name the CLI will export aws-pinpoint
? description Simple utility for creating, updating, and deleting aws pinpoint projects
? author Paul Rene Nichols
? version 0.0.0
? license MIT
? Who is the GitHub owner of repository (https://github.com/OWNER/repo) aws-utilities
? What is the GitHub name of repository (https://github.com/owner/REPO) aws-pinpoint
? Select a package manager npm
? TypeScript No
? Use eslint (linter for JavaScript) Yes
? Use mocha (testing framework) Yes
? Add CI service config circleci (continuous integration/delivery service)
TypeError: entry.isFile is not a function
    at EntryFilter.onlyFileFilter (~/.npm/_npx/16937/lib/node_modules/oclif/node_modules/fast-glob/out/providers/filters/entry.js:56:49)
    at EntryFilter.filter (~/.npm/_npx/16937/lib/node_modules/oclif/node_modules/fast-glob/out/providers/filters/entry.js:32:18)
    at ~/.npm/_npx/16937/lib/node_modules/oclif/node_modules/fast-glob/out/providers/filters/entry.js:18:48
    at ~/.npm/_npx/16937/lib/node_modules/oclif/node_modules/fast-glob/out/adapters/fs-sync.js:32:36
    at Array.forEach (<anonymous>)
    at FileSystemSync.read (~/.npm/_npx/16937/lib/node_modules/oclif/node_modules/fast-glob/out/adapters/fs-sync.js:29:18)
    at ReaderSync.staticApi (~/.npm/_npx/16937/lib/node_modules/oclif/node_modules/fast-glob/out/providers/reader-sync.js:70:31)
    at ReaderSync.api (~/.npm/_npx/16937/lib/node_modules/oclif/node_modules/fast-glob/out/providers/reader-sync.js:58:21)
    at ReaderSync.read (~/.npm/_npx/16937/lib/node_modules/oclif/node_modules/fast-glob/out/providers/reader-sync.js:41:32)
    at Array.map (<anonymous>)
➜  aws-utilities 
```

What is the expected behavior?
------------------------------
I expect to generate working source files for a multi command stub.

Pretty sure oclif version is v1.12.8 and OS is macOS Mojave Version 10.14.2

**Comment by mrmlnc** [comment]
Sorry, this is related to https://github.com/mrmlnc/fast-glob/issues/144.

**Comment by paulrenenichols** [comment]
@mrmlnc Thanks for reverting latest so quickly!
