### ISSUE TITLE
Testing interactive commands

### ISSUE THREAD

**Issue by mhemrg** [oclif/oclif#286]
Hey, well done.
How can I test interactive commands? For example, I have a login command which uses `inquirer` to ask the user for his email and password. With current testing utilities, I don't know how can I test these scenarios.

**Comment by mhemrg** [comment]
I think [Nixt](https://www.npmjs.com/package/nixt) is solving this by providing a `.on()` method.
 [Responding to interactive prompts](https://www.npmjs.com/package/nixt#responding-to-interactive-prompts)

**Comment by mhemrg** [comment]
@RasPhilCo Thank you for your comment.
Can you please share an example of those approaches?

**Comment by gingermusketeer** [comment]
This is what I ended up doing to solve this:
```ts
import * as prompter from "cli-ux/lib/prompt";
// ...
  test
    // @ts-ignore
    .stub(prompter, "prompt", (msg) => {
      expect(msg).to.eql("Please enter your token");
      return "pizza-token";
    })
    .stdout()
    .stderr()
    .command(["login"])
    .it("handles scopes being wrong", (ctx) => {

      expect(ctx.stderr).to.be.empty;
    });
```

**Comment by Souvikns** [comment]
I am trying to use inquirer but it is not working, it just does not resolve. The test just keeps on running


This is what I am trying to do 
```ts
describe('new', () => {
    test
        .stub(inquirer, 'prompt', () => async () => 'somefile.yaml\n')
        .stub(inquirer, 'prompt', () => async () => 'n\n')
        .stub(inquirer, 'prompt', () => async () => 'n\n')
        .stderr()
        .stdout()
        .command(['new'])
        .it('runs new command', (ctx, done) => {
            done(); 
        });
});
```

**Comment by yanxiaodi** [comment]
I have the same question. I have multiple questions in `inquirer` prompts. Is there any way to respond to this kind of prompts? Thanks.

@RasPhilCo Could you please share your example? Many thanks.

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.

**Comment by johnitvn** [comment]
I found a way to be able to do the test for multiple questions in inquirer prompts

in the main cli file like this:
```typescript
 let framework: string = (await inquirer.prompt([{
      name: 'framework',
      message: 'Choose frontend framework',
      type: 'list',
      choices: [ { name: 'angular'}, { name: 'reactjs'} ],
    }])).framework;

   let template: string = (await inquirer.prompt([{
      name: 'template',
      message: 'Choose frontend framework',
      type: 'list',
      choices: [ { name: 'minimal'}, { name: 'sidebar'} ],
    }])).template;

    this.log(`Template: ${framework}@${template}`);
```

in the test file like this:

```typescript
test
    .stdout({ print: true })
    .stub(inquirer, 'prompt', () => Promise.resolve(
          {
            framework: 'angular',
            template: 'minimal'
          }
      )
    )
    .command(['new', path.join(__dirname, "tmp")])
    .it('Testing create output success', ctx => {
      expect(ctx.stdout).to.contain("Template: angular@minima");
    });

```

Hope this can help someone!!!

**Comment by BravoNatalie** [comment]
@johnitvn I've tried your solution, but I keep having the `TypeError: Cannot redefine property: prompt` error.


My command file:
```ts
const deploymentTypePrompt: any = await inquirer.prompt([
      {
        name: 'deploymentType',
        message: prompt,
        type: 'list',
        choices: deploymentProcesses,
      },
    ])
```

Test file:
```ts
import {expect, test} from '@oclif/test'
import * as inquirer from 'inquirer'

process.env['ABI_ENVIRONMENT'] = 'localhost'

describe('create:contract', () => {
  test
    .stdout({print: true})
    .stub(inquirer, 'prompt', () =>
      Promise.resolve({
        deploymentTypePrompt: 'createConfig',
      }),
    )
    .command(['create:contract'])
    .it('runs create:contract cmd', ctx => {
      // expect(ctx.stdout).to.contain('')
    })
})
```

Error:
```sh
1) create:contract
       runs create:contract cmd:
     TypeError: Cannot redefine property: prompt
      at Function.defineProperty (<anonymous>)
      at Object.run (node_modules/fancy-test/lib/stub.js:18:24)
      at Context.run (node_modules/fancy-test/lib/base.js:68:36)
```

**Comment by thetutlage** [comment]
Check https://github.com/poppinss/prompts/tree/develop. Built specifically to make testing easier.

**Comment by AlbertoMata** [comment]
I have found a way to test multiple calls to `ux.prompt`, no extra libraries
needed aside from the default `@oclif/core` (which is actually an extension of
`fancy-test`):

Let's suppose we have a single-command-cli `Hello`, then our `src/index.ts` file
would look like this:

```
import {Command, Flags, ux} from '@oclif/core'

export default class Hello extends Command {
  static description = 'describe the command here'

  static examples = [
    `$ myplugin hello
hello world from ./src/hello.ts!
`,
  ]

  static flags = {
    help: Flags.help({char: 'h'}),
    // add --version flag to show CLI version
    version: Flags.version({char: 'v'}),
  }

  interactive = async () => {
    const object = {
      email: '',
      name: '',
      phone: '',
    }

    const name = await ux.prompt('What is your name?')
    const email = await ux.prompt('What is your email?')
    const phone = await ux.prompt('What is your phone number?')

    object.name = name
    object.email = email
    object.phone = phone

    return object
  }

  async run(): Promise<void> {
    const object = await this.interactive()

    console.log(`Hello ${object.name}!`)
  }
}
```

Our `test/index.test.tes` file will look like this: 

```

import {ux} from '@oclif/core'
import {expect, test} from '@oclif/test'

import Hello from '../src/index'

const promptStub = (stub) => {
  stub.onFirstCall().resolves('John Doe') // Alias for stub.onCall(0).resolves('John Doe')
  stub.onSecondCall().resolves('john.doe@foobar.com') // Alias for stub.onCall(1).resolves('john.doe@foobar.com') 
  stub.onThirdCall().resolves('123-456-7890') // Alias for stub.onCall(2).resolves('123-456-7890')
  return stub
}

describe('basic usage', () => {
  test
    .stdout()
    .stub(ux, 'prompt', promptStub)
    .do(() => Hello.run([]))
    .it('runs hello', (ctx) => {
      expect(ctx.stdout).to.contain('Hello John Doe!')
    })
})


```

We need understand that `stub` is part of the
[Sinon.JS](https://sinonjs.org/releases/latest/stubs/) library, and that we can
use some of the `stub` features in our `oclif` tests. Data types are specially
important if we are using TypeScript.  

In addition, to test multiple-command-cli's just replace `.do(() =>
Hello.run([]))` with the regular `.command()` calls.

**Comment by AlbertoMata** [comment]
I have found a way to test multiple calls to `ux.prompt`, no extra libraries
needed aside from the default `@oclif/core` (which is actually an extension of
`fancy-test`):

Let's suppose we have a single-command-cli `Hello`, then our `src/index.ts` file
would look like this:

```ts
import {Command, Flags, ux} from '@oclif/core'

export default class Hello extends Command {
  static description = 'describe the command here'

  static examples = [
    `$ myplugin hello
hello world from ./src/hello.ts!
`,
  ]

  static flags = {
    help: Flags.help({char: 'h'}),
    // add --version flag to show CLI version
    version: Flags.version({char: 'v'}),
  }

  interactive = async () => {
    const object = {
      email: '',
      name: '',
      phone: '',
    }

    const name = await ux.prompt('What is your name?')
    const email = await ux.prompt('What is your email?')
    const phone = await ux.prompt('What is your phone number?')

    object.name = name
    object.email = email
    object.phone = phone

    return object
  }

  async run(): Promise<void> {
    const object = await this.interactive()

    console.log(`Hello ${object.name}!`)
  }
}
```

Our `test/index.test.tes` file will look like this: 

```ts

import {ux} from '@oclif/core'
import {expect, test} from '@oclif/test'

import Hello from '../src/index'

const promptStub = (stub) => {
  stub.onFirstCall().resolves('John Doe') // Alias for stub.onCall(0).resolves('John Doe')
  stub.onSecondCall().resolves('john.doe@foobar.com') // Alias for stub.onCall(1).resolves('john.doe@foobar.com') 
  stub.onThirdCall().resolves('123-456-7890') // Alias for stub.onCall(2).resolves('123-456-7890')
  return stub
}

describe('basic usage', () => {
  test
    .stdout()
    .stub(ux, 'prompt', promptStub)
    .do(() => Hello.run([]))
    .it('runs hello', (ctx) => {
      expect(ctx.stdout).to.contain('Hello John Doe!')
    })
})


```

We need understand that `stub` is part of the [Sinon.JS](https://sinonjs.org/releases/latest/stubs/) library, and that we can use some of the `stub` features in our `oclif` tests. Data types are specially important if we are using TypeScript.  

In addition, to test multiple-command-cli's just replace `.do(() => Hello.run([]))` with the regular `.command()` calls.

**Comment by AlbertoMata** [comment]
I have found a way to test multiple calls to `ux.prompt`, no extra libraries needed aside from the default `@oclif/core` (which is actually an extension of `fancy-test`):

Let's suppose we have a single-command-cli `Hello`, then our `src/index.ts` file would look like this:

```ts
import {Command, Flags, ux} from '@oclif/core'

export default class Hello extends Command {
  static description = 'describe the command here'

  static examples = [
    `$ myplugin hello
hello world from ./src/hello.ts!
`,
  ]

  static flags = {
    help: Flags.help({char: 'h'}),
    // add --version flag to show CLI version
    version: Flags.version({char: 'v'}),
  }

  interactive = async () => {
    const object = {
      email: '',
      name: '',
      phone: '',
    }

    const name = await ux.prompt('What is your name?')
    const email = await ux.prompt('What is your email?')
    const phone = await ux.prompt('What is your phone number?')

    object.name = name
    object.email = email
    object.phone = phone

    return object
  }

  async run(): Promise<void> {
    const object = await this.interactive()

    console.log(`Hello ${object.name}!`)
    console.log(`Your email is ${object.email}`)
    console.log(`Your phone number is ${object.phone}`)
  }
}
```

Our `test/index.test.tes` file will look like this: 

```ts

import {ux} from '@oclif/core'
import {expect, test} from '@oclif/test'

import Hello from '../src/index'

const promptStub = (stub) => {
  stub.onFirstCall().resolves('John Doe') // Alias for stub.onCall(0).resolves('John Doe')
  stub.onSecondCall().resolves('john.doe@foobar.com') // Alias for stub.onCall(1).resolves('john.doe@foobar.com') 
  stub.onThirdCall().resolves('123-456-7890') // Alias for stub.onCall(2).resolves('123-456-7890')
  return stub
}

describe('basic usage', () => {
  test
    .stdout({print: true})
    .stub(ux, 'prompt', promptStub)
    .do(() => Hello.run([]))
    .it('runs hello', (ctx) => {
      expect(ctx.stdout).to.contain('Hello John Doe!')
      expect(ctx.stdout).to.contain('Your email is john.doe@foobar.com')
      expect(ctx.stdout).to.contain('Your phone number is 123-456-7890')
    })
})


```

We need understand that `stub` is part of the [Sinon.JS](https://sinonjs.org/releases/latest/stubs/) library, and that we can use some of the `stub` features in our `oclif` tests. Data types are specially important if we are using TypeScript.  

In addition, to test multiple-command-cli's just replace `.do(() => Hello.run([]))` with the regular `.command()` calls.
