### ISSUE TITLE
Unable to use oclif behind corporate proxy 

### ISSUE THREAD

**Issue by adanilev** [oclif/oclif#313]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Bug?

What is the current behavior?
-----------------------------
I'm behind a corporate proxy at work. When running `npx oclif multi mycli`, oclif installs fine but hangs AFTER showing the yeoman ascii face and BEFORE the prompt asking for the npm package name. 

I think the problem is somewhere in `src/generators/app.ts` between lines 142 and 170. Sorry, don't have time atm to track it down further.

What is the expected behavior?
------------------------------
The project can scaffold correctly behind a proxy when npm / yarn are configured correctly to use the proxy and private registries.

oclif 1.15.1
macOS 10.14.5

**Comment by rulatir** [comment]
For me it freezes AFTER the prompt asking for the npm package name. I am not behind a corporate proxy, but I don't have a public IP either (village-style ISP).

**Comment by RasPhilCo** [comment]
Do you have HTTPS_PROXY or HTTP_PROXY set?

**Comment by adanilev** [comment]
@RasPhilCo, yes. Both in upper and lower case.

**Comment by RasPhilCo** [comment]
https://github.com/oclif/oclif/blob/master/src/generators/app.ts#L146

Yeoman makes a call to GitHub to get your username, we are catching this call so it must never return.

To confirm, can you install yeoman `$ npm install -g yo` which will run `yo doctor`. Also helpful, run oclif in debug mode `DEBUG=*` and view the debug output of where it hangs.

**Comment by adanilev** [comment]
Turns out I was being impatient. `yo doctor` complains about the self-signed certificate presented our Artifactory despite `strict-ssl` being set to false in .npmrc. 

While typing up this response, the call eventually timed out and the prompt appeared. I was then able to create the package normally. So it looks to be an issue with yeoman.

Thanks for your quick responses @RasPhilCo!

```shell
~/Desktop
❯ DEBUG=* npx oclif multi mycli
  @oclif/config reading core plugin /Users/xxxxxxx/.npm/_npx/23589/lib/node_modules/oclif +0ms
  @oclif/config loadJSON /Users/xxxxxxx/.npm/_npx/23589/lib/node_modules/oclif/package.json +0ms
  @oclif/config loadJSON /Users/xxxxxxx/.npm/_npx/23589/lib/node_modules/oclif/oclif.manifest.json +1ms
  @oclif/config loadJSON /Users/xxxxxxx/.npm/_npx/23589/lib/node_modules/oclif/.oclif.manifest.json +1ms
  @oclif/config:oclif loading IDs from /Users/xxxxxxx/.npm/_npx/23589/lib/node_modules/oclif/lib/commands +0ms
  @oclif/config:oclif found commands [ 'base', 'command', 'hook', 'multi', 'plugin', 'single' ] +8ms
  @oclif/config:oclif require /Users/xxxxxxx/.npm/_npx/23589/lib/node_modules/oclif/lib/commands/base.js +3ms
  @oclif/config:oclif require /Users/xxxxxxx/.npm/_npx/23589/lib/node_modules/oclif/lib/commands/command.js +324ms
  @oclif/config:oclif require /Users/xxxxxxx/.npm/_npx/23589/lib/node_modules/oclif/lib/commands/hook.js +1ms
  @oclif/config:oclif require /Users/xxxxxxx/.npm/_npx/23589/lib/node_modules/oclif/lib/commands/multi.js +1ms
  @oclif/config:oclif require /Users/xxxxxxx/.npm/_npx/23589/lib/node_modules/oclif/lib/commands/plugin.js +1ms
  @oclif/config:oclif require /Users/xxxxxxx/.npm/_npx/23589/lib/node_modules/oclif/lib/commands/single.js +0ms
  @oclif/config reading user plugins pjson /Users/xxxxxxx/.local/share/oclif/package.json +0ms
  @oclif/config loadJSON /Users/xxxxxxx/.local/share/oclif/package.json +357ms
  @oclif/config loading plugins [ '@oclif/plugin-help',
  '@oclif/plugin-warn-if-update-available',
  '@oclif/plugin-not-found' ] +2ms
  @oclif/config reading core plugin /Users/xxxxxxx/.npm/_npx/23589/lib/node_modules/oclif/node_modules/@oclif/plugin-help +0ms
  @oclif/config loadJSON /Users/xxxxxxx/.npm/_npx/23589/lib/node_modules/oclif/node_modules/@oclif/plugin-help/package.json +3ms
  @oclif/config reading core plugin /Users/xxxxxxx/.npm/_npx/23589/lib/node_modules/oclif/node_modules/@oclif/plugin-warn-if-update-available +0ms
  @oclif/config loadJSON /Users/xxxxxxx/.npm/_npx/23589/lib/node_modules/oclif/node_modules/@oclif/plugin-warn-if-update-available/package.json +0ms
  @oclif/config reading core plugin /Users/xxxxxxx/.npm/_npx/23589/lib/node_modules/oclif/node_modules/@oclif/plugin-not-found +0ms
  @oclif/config loadJSON /Users/xxxxxxx/.npm/_npx/23589/lib/node_modules/oclif/node_modules/@oclif/plugin-not-found/package.json +0ms
  @oclif/config loadJSON /Users/xxxxxxx/.npm/_npx/23589/lib/node_modules/oclif/node_modules/@oclif/plugin-help/oclif.manifest.json +1ms
  @oclif/config loadJSON /Users/xxxxxxx/.npm/_npx/23589/lib/node_modules/oclif/node_modules/@oclif/plugin-not-found/oclif.manifest.json +0ms
  @oclif/config loadJSON /Users/xxxxxxx/.npm/_npx/23589/lib/node_modules/oclif/node_modules/@oclif/plugin-warn-if-update-available/oclif.manifest.json +1ms
  @oclif/config:@oclif/plugin-help using manifest from /Users/xxxxxxx/.npm/_npx/23589/lib/node_modules/oclif/node_modules/@oclif/plugin-help/oclif.manifest.json +0ms
  @oclif/config:@oclif/plugin-not-found using manifest from /Users/xxxxxxx/.npm/_npx/23589/lib/node_modules/oclif/node_modules/@oclif/plugin-not-found/oclif.manifest.json +0ms
  @oclif/config:@oclif/plugin-warn-if-update-available using manifest from /Users/xxxxxxx/.npm/_npx/23589/lib/node_modules/oclif/node_modules/@oclif/plugin-warn-if-update-available/oclif.manifest.json +0ms
  @oclif/config config done +3ms
  @oclif/config start init hook +1ms
  oclif:@oclif/plugin-warn-if-update-available:hooks:init start /Users/xxxxxxx/.npm/_npx/23589/lib/node_modules/oclif/node_modules/@oclif/plugin-warn-if-update-available/lib/hooks/init/check-update +0ms
  oclif:@oclif/plugin-warn-if-update-available:hooks:init done +28ms
  @oclif/config init hook done +28ms
  oclif init version: @oclif/command@1.5.19 argv: [ 'multi', 'mycli' ] +0ms
  @oclif/config runCommand multi [ 'mycli' ] +4ms
  @oclif/config:oclif require /Users/xxxxxxx/.npm/_npx/23589/lib/node_modules/oclif/lib/commands/multi.js +41ms
  @oclif/config start prerun hook +1ms
  @oclif/config prerun hook done +1ms
  oclif:multi init version: @oclif/command@1.5.19 argv: [ 'mycli' ] +0ms
  yeoman:environment Registered oclif:app (/Users/xxxxxxx/.npm/_npx/23589/lib/node_modules/oclif/lib/generators/app.js) on package (undefined) +0ms
  yeoman:generator Queueing prompting in prompting +0ms
  yeoman:generator Queueing writing in writing +1ms
  yeoman:generator Queueing install in install +0ms
  yeoman:generator Queueing end in end +0ms
  yeoman:generator Running prompting +4ms

     _-----_     ╭──────────────────────────╮
    |       |    │      Time to build a     │
    |--(o)--|    │  multi-command CLI with  │
   `---------´   │  oclif! Version: 1.15.2  │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

  generator-oclif RequestError: connect ETIMEDOUT x.x.x.x:443
  generator-oclif     at ClientRequest.req.once.err (/Users/xxxxxxx/.npm/_npx/23589/lib/node_modules/oclif/node_modules/got/index.js:111:21)
  generator-oclif     at Object.onceWrapper (events.js:286:20)
  generator-oclif     at ClientRequest.emit (events.js:198:13)
  generator-oclif     at TLSSocket.socketErrorListener (_http_client.js:392:9)
  generator-oclif     at TLSSocket.emit (events.js:198:13)
  generator-oclif     at emitErrorNT (internal/streams/destroy.js:91:8)
  generator-oclif     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
  generator-oclif     at process._tickCallback (internal/process/next_tick.js:63:19) +0ms
? npm package name we-got-there-eventually
```
