### ISSUE TITLE
Bug: declaration file for lib without typings

### ISSUE THREAD

**Issue by smwbtech** [oclif/oclif#335]
Do you want to request *bug*?
-----------------------------------------------------

What is the current behavior?

```bash
TSError: ⨯ Unable to compile TypeScript:
src/index.ts:2:26 - error TS7016: Could not find a declaration file for module 'read-excel-file/node'. '/Users/romanprivlov/Desktop/Projects/email-scraper-cli/node_modules/read-excel-file/node.js' implicitly has an 'any' type.
  Try `npm install @types/read-excel-file` if it exists or add a new declaration (.d.ts) file containing `declare module 'read-excel-file/node';`

2 import readXlsxFile from 'read-excel-file/node';
                           ~~~~~~~~~~~~~~~~~~~~~~

    at createTSError (/Users/romanprivlov/Desktop/Projects/email-scraper-cli/node_modules/ts-node/src/index.ts:421:12)
    at reportTSError (/Users/romanprivlov/Desktop/Projects/email-scraper-cli/node_modules/ts-node/src/index.ts:425:19)
    at getOutput (/Users/romanprivlov/Desktop/Projects/email-scraper-cli/node_modules/ts-node/src/index.ts:530:36)
    at Object.compile (/Users/romanprivlov/Desktop/Projects/email-scraper-cli/node_modules/ts-node/src/index.ts:735:32)
    at Module.m._compile (/Users/romanprivlov/Desktop/Projects/email-scraper-cli/node_modules/ts-node/src/index.ts:814:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/romanprivlov/Desktop/Projects/email-scraper-cli/node_modules/ts-node/src/index.ts:817:12)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)`
```
-----------------------------
If the current behavior is a bug, please provide the steps to reproduce.

1. `npm i read-excel-file`

2. Import it in index.ts file
```js
import readXlsxFile from 'read-excel-file/node';
```

3. Add decs.d.ts file 
``` javascript
declare module 'read-excel-file/node';
```
4. Add declaration file to tsconfig/include

```json
"include": [
		"src/**/*",
		"node_modules/@types/puppeteer/index.d.ts",
		"src/@types/decs.d.ts"
	]
```
5. Run `./bin/run`

What is the expected behavior?

Should run correctly and open and read file, if user pass path to the file
------------------------------
oclif 1.5.19 / macOS Catalina 10.15.3
[reproduction repo](https://github.com/smwbtech/email-scraper-cli)

**Comment by RasPhilCo** [comment]
Good to know for this package. Though it's not a bug in oclif.

**Comment by RasPhilCo** [comment]
Cleaning up - if you think this issue is still valid, reopen it. Thanks!

**Comment by ido50** [comment]
I've had the same issue with a different package when using `bin/dev` (haven't tried `bin/run` yet). The workaround was to enable ts-node's "files" option. In bin/dev, replace this line:

```js
require('ts-node').register({project})
```
with this line:

```js
require('ts-node').register({project, files: true})
```
