### ISSUE TITLE
Bug: Invalid flags validation is lost when extending the base Command class

### ISSUE THREAD

**Issue by jfoliveira** [oclif/oclif#374]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Bug

What is the current behavior?
-----------------------------
Invalid flags validation is not handled when a command extends a custom base Command class.
Command to reproduce the issue:
```shell
$ ./bin/run test:cmd --some_unknow_flag='invalid' --name='My name valid  flag value'
```

After defining a minimal base `Command` class and make my command inherits from it - as instructed in [the docs](https://oclif.io/docs/base_class) - the invalid flag exception is thrown as uncaught:

```shell
 (node:67320) UnhandledPromiseRejectionWarning: Error: Unexpected argument: --jsome_unknow_flag=invalid
See more help with --help
    at validateArgs (/Users/dev/my-cli/node_modules/@oclif/parser/lib/validate.js:10:19)
    at Object.validate (/Users/dev/my-cli/node_modules/@oclif/parser/lib/validate.js:55:5)
    at Object.parse (/Users/dev/my-cli/node_modules/@oclif/parser/lib/index.js:28:7)
    at ProjectAdd.parse (/Users/dev/my-cli/node_modules/@oclif/command/lib/command.js:86:41)
    at ProjectAdd.run (/Users/dev/my-cli/src/commands/test/cmd.ts:20:34)
    at ProjectAdd._run (/Users/dev/my-cli/node_modules/@oclif/command/lib/command.js:43:31)
(node:67320) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:67320) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

What is the expected behavior?
------------------------------
"@oclif/dev-cli": "^1.22.2",
"@oclif/command": "^1.6.1",
macOS Catalina

I would expect the same error message to be displayed handling the exception gracefully, as it does when my command inherits the default command class:
```javascript
 ›   Error: Unexpected argument: --some_unknow_flag=invalid
 ›   See more help with --help
```

**My base command class definition:**
```javascript
import Command, { flags } from '@oclif/command'
import cli from 'cli-ux'

export default abstract class extends Command {
    async init() {
        //
    }

    async catch(err: any): Promise<any> {
        if (err && err?.status) {
            cli.styledHeader(`${this.id}: ${err}`);
            if (err.errors) {
                cli.styledObject(err.errors);
            }
        }
        super.catch(err);
    }

    async finally(_: Error | undefined): Promise<any> {
        super.finally(_);
    }
}
 ```

Is there anything I am missing that should be part of my custom command class in order to honor the default command behaviour?

**Comment by jfoliveira** [comment]
Figured it out: I was missing the `return` clause in both `catch` and `finally` methods.
It might be useful to add that to the example in the docs. I opened a PR for that:
https://github.com/oclif/oclif.github.io/pull/83 

Hope it helps others!
