### ISSUE TITLE
Integrating YEOMAN for custom generators

### ISSUE THREAD

**Issue by francisminu** [oclif/oclif#398]
This is neither a feature request nor a bug. 
I am trying to implement YEOMAN-GENERATORS in my cli that I have created using OCLIF. I have been following the official documentation and did the below in the command class in my cli:

(Below given is my Command class)

    import { Command } from "@oclif/command";
    import { createEnv } from 'yeoman-environment'

    export default class CsGenerator extends Command {
    static description = 'Generate hosted service 1';
    async run() {
    const env = createEnv()
     env.register(require.resolve('../generators/component1'), `oclif:component1`);
     console.log('test')
      env.run('oclif:component1', (err: any, stdout: any, stderr: any) => {
        console.log(err);
      });
     }
    }

I am getting the below error on env.run:
**TypeError: Class extends value #<Object> is not a constructor or null**
    at Object.<anonymous> (C:/Project/SynapseModernization/2020/cli/src/generators/component1.ts:5:42)
    at Module.m._compile (C:/Project/SynapseModernization/2020/cli/node_modules/ts-node/src/index.ts:439:23)
    at Object.require.extensions.(anonymous function) [as .ts] (C:/Project/SynapseModernization/2020/cli/node_modules/ts-node/src/index.ts:442:12)
    at Object.get [as oclif:component1] (C:/Project/SynapseModernization/2020/cli/node_modules/yeoman-environment/lib/store.js:47:27)
    at Store.get (C:/Project/SynapseModernization/2020/cli/node_modules/yeoman-environment/lib/store.js:71:39)
    at Environment.get (C:/Project/SynapseModernization/2020/cli/node_modules/yeoman-environment/lib/environment.js:540:48)
    at Environment.create (C:/Project/SynapseModernization/2020/cli/node_modules/yeoman-environment/lib/environment.js:613:37)
    at instantiateAndRun (C:/Project/SynapseModernization/2020/cli/node_modules/yeoman-environment/lib/environment.js:729:30)
    at Environment.run (C:/Project/SynapseModernization/2020/cli/node_modules/yeoman-environment/lib/environment.js:758:12)
    at CsGenerator.run (C:/Project/SynapseModernization/2020/cli/src/commands/component1.ts:19:9)
    at CsGenerator._run (C:/Project/SynapseModernization/2020/cli/node_modules/@oclif/command/lib/command.js:35:31)

Any input is greatly appreciated.

**Comment by 0xdevalias** [comment]
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
