### ISSUE TITLE
Bug - Error: EEXIT: 0 when running --help and -h 

### ISSUE THREAD

**Issue by juanjoman** [oclif/oclif#427]
What is the current behavior?
-----------------------------
Good morning, I'm trying to use the --help and -h option to see the help information from my command but I'm receiving the following error **plus the help information:**
```
➜  booster git:(master) ✗ boost new:command -h    
generate new resource, write 'boost new' to see options

USAGE
  $ boost new:command [COMMANDNAME]

OPTIONS
  -f, --fields=fields  field that this command will contain
  -h, --help           show CLI help

ExitError: EEXIT: 0
    at Object.exit (/Users/.../.nvm/versions/node/v14.2.0/lib/node_modules/@boostercloud/cli/node_modules/@oclif/errors/lib/index.js:19:11)
    at Command.exit (/Users/.../.nvm/versions/node/v14.2.0/lib/node_modules/@boostercloud/cli/node_modules/@oclif/command/lib/command.js:54:23)
    at Command._help (/Users/.../.nvm/versions/node/v14.2.0/lib/node_modules/@boostercloud/cli/node_modules/@oclif/command/lib/command.js:127:21)
    at Object.parse (/Users/.../.nvm/versions/node/v14.2.0/lib/node_modules/@boostercloud/cli/node_modules/@oclif/command/lib/flags.js:37:17)
    at Parser._flags (/Users/.../.nvm/versions/node/v14.2.0/lib/node_modules/@boostercloud/cli/node_modules/@oclif/parser/lib/parse.js:149:42)
    at Parser.parse (/Users/.../.nvm/versions/node/v14.2.0/lib/node_modules/@boostercloud/cli/node_modules/@oclif/parser/lib/parse.js:117:28)
    at Object.parse (/Users/.../.nvm/versions/node/v14.2.0/lib/node_modules/@boostercloud/cli/node_modules/@oclif/parser/lib/index.js:27:27)
    at Command.parse (/Users/.../.nvm/versions/node/v14.2.0/lib/node_modules/@boostercloud/cli/node_modules/@oclif/command/lib/command.js:86:41)
    at Command.runWithErrors (/Users/.../.nvm/versions/node/v14.2.0/lib/node_modules/@boostercloud/cli/dist/commands/new/command.js:16:38)
    at Command.run (/Users/.../.nvm/versions/node/v14.2.0/lib/node_modules/@boostercloud/cli/dist/commands/new/command.js:13:21) {
  oclif: { exit: 0 },
  code: 'EEXIT'
```

Here's the branch with the changes:
1. Command: https://github.com/boostercloud/booster/blob/cli_help_error/packages/cli/src/commands/new/command.ts
2. Test: https://github.com/boostercloud/booster/blob/cli_help_error/packages/cli/test/commands/new.test.ts

The thing is that "unchained commands" (like `boost start -h`) are working, but not the chained ones, like 
`boost new:event -h`

What is the expected behavior?
------------------------------
I would like to avoid printing that `Error: EEXIT: 0`, and only print the --help information

Does anyone know what is going on?

**Comment by MwumLi** [comment]
haven't fixed yet?

**Comment by juanjoman** [comment]
Hey @MwumLi I think we haven't fixed this yet. By the way, if you're going to contribute feel free to come to our discord and ask anything you want :) https://discord.gg/bDY8MKx

**Comment by NickSeagull** [comment]
Just tried this and with the newest version of oclif it looks like it doesn't happen. Can you confirm @juanjoman ?

**Comment by juanjoman** [comment]
Yep not happening anymore to me, closing this. cc @MwumLi

**Comment by busticated** [comment]
i just ran into this after upgrading `@oclif/plugin-help` to `v3.2.13` - it happens when i invoke the help output:

```
Test the update

USAGE
  $ mycli test [COUNT]

ARGUMENTS
  COUNT  [default: Infinity] The maximum number of foos to bar

OPTIONS
  --silent          Silent command output
  --verbose         Output verbose error detail

EXAMPLES
  $ mycli test
  $ mycli test 4

 ›   Error: EEXIT: 0
 ›   Code: EEXIT
```

downgrading to `v3.2.3` seems to fix it
