### ISSUE TITLE
Hooks are not functioning

### ISSUE THREAD

**Issue by jercle** [oclif/oclif#902]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Bug
What is the current behavior?
-----------------------------
No hooks are firing when running the cli.
I've also tried starting a project from scratch, same issue.
Have tried using the `init` hook (using `oclif generate hook myhook --event=init`) as well as creating a custom hook using as per docs: https://oclif.io/docs/hooks

<img width="408" alt="image" src="https://user-images.githubusercontent.com/10472533/174532364-09bfaa27-521d-4487-9522-03a0cdad6336.png">

What is the expected behavior?
------------------------------
Please mention your oclif and OS version.
oclif versions:
* oclif/3.0.1 darwin-arm64 node-v16.15.1
* oclif/3.0.1 darwin-arm64 node-v18.4.0
* oclif/2.6.3 darwin-arm64 node-v16.15.1
* oclif/2.6.3 darwin-arm64 node-v18.4.0

OSes: 
* macOS Monterey | 12.1
* Windows 10

Example code: https://github.com/jercle/azgo/tree/45c62d8cacd9f85af10422ca1b4b97e842ff2533/azgoc

Edit: removed freshly generated code as I deleted the repo

**Comment by jercle** [comment]
Found how to enable debugging. The following is shown when debugging:

```bash
  azgoc:azgoc:hooks:init /Users/jercle/git/azgo/azgoc/src/hooks/init/auth.ts:1
  azgoc:azgoc:hooks:init import {Hook} from '@oclif/core'
  azgoc:azgoc:hooks:init ^^^^^^
  azgoc:azgoc:hooks:init 
  azgoc:azgoc:hooks:init SyntaxError: Cannot use import statement outside a module
  azgoc:azgoc:hooks:init     at Object.compileFunction (node:vm:353:18)
  azgoc:azgoc:hooks:init     at wrapSafe (node:internal/modules/cjs/loader:1040:15)
  azgoc:azgoc:hooks:init     at Module._compile (node:internal/modules/cjs/loader:1076:27)
  azgoc:azgoc:hooks:init     at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
  azgoc:azgoc:hooks:init     at Module.load (node:internal/modules/cjs/loader:988:32)
  azgoc:azgoc:hooks:init     at Module._load (node:internal/modules/cjs/loader:834:12)
  azgoc:azgoc:hooks:init     at Module.require (node:internal/modules/cjs/loader:1012:19)
  azgoc:azgoc:hooks:init     at require (node:internal/modules/cjs/helpers:102:18)
  azgoc:azgoc:hooks:init     at ModuleLoader.loadWithData (/Users/jercle/git/azgo/azgoc/node_modules/.pnpm/@oclif+core@1.9.3/node_modules/@oclif/core/lib/module-loader.js:80:88)
  azgoc:azgoc:hooks:init     at /Users/jercle/git/azgo/azgoc/node_modules/.pnpm/@oclif+core@1.9.3/node_modules/@oclif/core/lib/config/config.js:233:87 +0ms
```

**Comment by jercle** [comment]
I have noticed it points the hook to run from the src folder instead of dist.
`"init": "./dist/hooks/init/myhook"`
