### ISSUE TITLE
Changing rootDir in package.json breaks command resolution

### ISSUE THREAD

**Issue by cayman-amzn** [oclif/oclif#921]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
bug

What is the current behavior?
-----------------------------
Change `rootDir` to `.` in `package.json`

These are the default commands and tests provided by the CLI command generator.
```
$ npm run test
...
> nyc mocha --forbid-only "test/**/*.test.ts"

  hello
    1) runs hello cmd

  hello world
    2) runs hello world cmd

  2 failing

  1) hello
       runs hello cmd:
     Error: command hello not found
      at Config.runCommand (node_modules/@oclif/core/lib/config/config.js:264:19)
      at async Object.run (node_modules/@oclif/test/lib/command.js:21:13)
      at async Context.run (node_modules/fancy-test/lib/base.js:68:25)

  2) hello world
       runs hello world cmd:
     Error: command hello:world not found
      at Config.runCommand (node_modules/@oclif/core/lib/config/config.js:264:19)
      at async Object.run (node_modules/@oclif/test/lib/command.js:21:13)
      at async Context.run (node_modules/fancy-test/lib/base.js:68:25)
...
```

What is the expected behavior?
------------------------------
```
$ npm run test
...
> nyc mocha --forbid-only "test/**/*.test.ts"
  hello
    ✔ runs hello cmd (304ms)

  hello world
    ✔ runs hello world cmd

...
```

```
# <snip> in <snip> on git:oclif-v3 x [3:04:33] 
$ uname -r
5.4.196-119.356.amzn2int.x86_64

# <snip> in <snip> on git:oclif-v3 x [3:04:35] 
$ oclif --version
oclif/3.0.1 linux-x64 node-v14.20.0
```

**Comment by mdonnalley** [comment]
@cayman-amzn I'm not surprised that changing the `rootDir` in the tsconfig would break the tests. By doing that your files will be compiled to `dist/src` so if that's what you want you also need to change `oclif.commands` to `./dist/src/commands` in the package.json
