### ISSUE TITLE
Project generator times out too quckly

### ISSUE THREAD

**Issue by mrthehud** [oclif/oclif#922]
When generating a new project, the command times out ("Error: timed out") in about 8 seconds.

```
$ DEBUG=* npx oclif generate tmp
npx: installed 581 in 27.291s
  config reading core plugin /home/james/.npm/_npx/938637/lib/node_modules/oclif +0ms
  config loadJSON /home/james/.npm/_npx/938637/lib/node_modules/oclif/package.json +0ms
  config loadJSON /home/james/.npm/_npx/938637/lib/node_modules/oclif/oclif.manifest.json +0ms
  config loadJSON /home/james/.npm/_npx/938637/lib/node_modules/oclif/.oclif.manifest.json +0ms
  config:oclif using manifest from /home/james/.npm/_npx/938637/lib/node_modules/oclif/.oclif.manifest.json +0ms
  config reading user plugins pjson /home/james/.local/share/oclif/package.json +0ms
  config loadJSON /home/james/.local/share/oclif/package.json +0ms
  config loading plugins [
  '@oclif/plugin-help',
  '@oclif/plugin-warn-if-update-available',
  '@oclif/plugin-not-found'
] +0ms
  config reading core plugin /home/james/.npm/_npx/938637/lib/node_modules/oclif/node_modules/@oclif/plugin-help +0ms
  config loadJSON /home/james/.npm/_npx/938637/lib/node_modules/oclif/node_modules/@oclif/plugin-help/package.json +0ms
  config reading core plugin /home/james/.npm/_npx/938637/lib/node_modules/oclif/node_modules/@oclif/plugin-warn-if-update-available +0ms
  config loadJSON /home/james/.npm/_npx/938637/lib/node_modules/oclif/node_modules/@oclif/plugin-warn-if-update-available/package.json +0ms
  config reading core plugin /home/james/.npm/_npx/938637/lib/node_modules/oclif/node_modules/@oclif/plugin-not-found +0ms
  config loadJSON /home/james/.npm/_npx/938637/lib/node_modules/oclif/node_modules/@oclif/plugin-not-found/package.json +0ms
  config loadJSON /home/james/.npm/_npx/938637/lib/node_modules/oclif/node_modules/@oclif/plugin-warn-if-update-available/oclif.manifest.json +0ms
  config loadJSON /home/james/.npm/_npx/938637/lib/node_modules/oclif/node_modules/@oclif/plugin-not-found/oclif.manifest.json +0ms
  config loadJSON /home/james/.npm/_npx/938637/lib/node_modules/oclif/node_modules/@oclif/plugin-help/oclif.manifest.json +0ms
  config:@oclif/plugin-warn-if-update-available using manifest from /home/james/.npm/_npx/938637/lib/node_modules/oclif/node_modules/@oclif/plugin-warn-if-update-available/oclif.manifest.json +0ms
  config:@oclif/plugin-not-found using manifest from /home/james/.npm/_npx/938637/lib/node_modules/oclif/node_modules/@oclif/plugin-not-found/oclif.manifest.json +0ms
  config:@oclif/plugin-help using manifest from /home/james/.npm/_npx/938637/lib/node_modules/oclif/node_modules/@oclif/plugin-help/oclif.manifest.json +0ms
  config config done +5ms
  config start init hook +0ms
  oclif:@oclif/plugin-warn-if-update-available:hooks:init start (require) /home/james/.npm/_npx/938637/lib/node_modules/oclif/node_modules/@oclif/plugin-warn-if-update-available/lib/hooks/init/check-update.js +0ms
  oclif:@oclif/plugin-warn-if-update-available:hooks:init done +3ms
  config init hook done +25ms
  config runCommand generate [ 'tmp' ] +0ms
  config:oclif (require) /home/james/.npm/_npx/938637/lib/node_modules/oclif/lib/commands/generate.js +359ms
  config start prerun hook +322ms
  config prerun hook done +0ms
  oclif:generate init version: @oclif/core@1.11.0 argv: [ 'tmp' ] +0ms
  yeoman:environment Registered oclif:cli (/home/james/.npm/_npx/938637/lib/node_modules/oclif/lib/generators/cli.js) on package oclif (undefined) +0ms
  yeoman:environment:namespace Parsed namespace YeomanNamespace { _original: 'oclif:cli', scope: undefined, unscoped: 'oclif', generator: 'cli', instanceId: undefined, semver: undefined, methods: undefined, flags: undefined } +0ms
  yeoman:generator Queueing generator undefined with generator version 5.6.1 +0ms
  yeoman:generator Queueing #prompting with options { priorityName: 'prompting', queueName: 'prompting', cancellable: true, run: false, auto: true, taskName: 'prompting' } +1ms
  yeoman:generator Queueing #writing with options { priorityName: 'writing', queueName: 'writing', cancellable: true, run: false, auto: true, taskName: 'writing' } +0ms
  yeoman:generator Queueing #end with options { priorityName: 'end', queueName: 'end', cancellable: true, run: false, auto: true, taskName: 'end' } +0ms
  yeoman:environment Queueing conflicts task +170ms
  config start postrun hook +175ms
  config postrun hook done +0ms
  yeoman:generator Running #prompting +2ms

     _-----_     
    |       |    ╭──────────────────────────╮
    |--(o)--|    │  Time to build an oclif  │
   `---------´   │    CLI! Version: 3.1.1   │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

Cloning into '/home/james/arqiva/fvp/tmp/grafana/tmp'...
? npm package name (tmp) Error: timed out
    at Object.error (/home/james/.npm/_npx/938637/lib/node_modules/oclif/node_modules/@oclif/core/lib/errors/index.js:29:15)
    at /home/james/.npm/_npx/938637/lib/node_modules/oclif/node_modules/@oclif/core/lib/cli-ux/index.js:25:66
    at async flush (/home/james/.npm/_npx/938637/lib/node_modules/oclif/node_modules/@oclif/core/lib/cli-ux/index.js:121:9)
```

**Comment by siv12345** [comment]
Same issue! I have tried with node v14 and v16.

**Comment by siv12345** [comment]
after using this command to view verbose logs 

`npx --loglevel verbose oclif generate myncli`

The process seems to have terminated here

`4720 verbose stack Error: process terminated
4720 verbose stack     at /home/siva/.nvm/versions/node/v16.16.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:199:39
4720 verbose stack     at process.<anonymous> (/home/siva/.nvm/versions/node/v16.16.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/signal-handling.js:51:5)
4720 verbose stack     at process.emit (node:events:539:35)
4721 verbose cwd /home/siva/RND/myncli`

have attached the debug.log 
[2022-07-19T12_48_43_533Z-debug-0.log](https://github.com/oclif/oclif/files/9141160/2022-07-19T12_48_43_533Z-debug-0.log)

**Comment by davidchalifoux** [comment]
Also running into this.
Node: 16.15.1
NPM: 8.11.0
macOS: 12.4 (M1)

**Comment by ajdruff** [comment]
Work around:

Depending on where it times out,  you may be able to just continue by running 

      npm i APP_NAME

If that completes, check that you have node_modules in your root directory. If you do, you are probably good. 

If that doesn't work or you timed out before the node_modules were generated,  this will work every time:

1. remove the files from the failed installation.

          rm -rf node_modules package-lock.json package.json APP_NAME 

2.  run the installation again but this time with a condition to restart on failure

           npx oclif generate APP_NAME ||  npm i APP_NAME/ 

At each of the prompts, don't bother trying to edit the answers and instead just hit enter at each prompt quickly enough so you don't time out until you've chosen your package manager ( npm or yarn) . It should timeout and fail during the npm install, but will then restart because of the OR condition that you added. 


3. Finally, edit your package.json since you didn't have time to enter your customizations.

           nano APP_NAME/package.json

**Comment by codespool** [comment]
I believe the bug is related to `cliUx.ux.flush` and the changed import introduced in v1.9.7:
https://github.com/oclif/core/compare/v1.9.6...v1.9.7

I've posted the description on https://github.com/oclif/core/issues/453

Temporary workaround is to lock the @oclif/core version to 1.9.6
