### ISSUE TITLE
Debugging in vscode not working (even using hello-world example)

### ISSUE THREAD

**Issue by DaelDe** [oclif/oclif#997]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
bug

What is the current behavior?
-----------------------------

1. checkout of [hello-world](https://github.com/oclif/hello-world)
1. npm install
1. added ` "sourceMap": true` to tsconfig.json
1. npm run build
1. /bin/run to verify everything

From the CLI the example is working, now try to debug in vscode, my launch.json is:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "program": "${workspaceFolder}\\bin\\run",
            "args": [
              "hello",
              "world",
            ],
        }
    ]
}
```

Set a breakpoint in `world.ts:17` (run method). 
Debug using the above configuration.

Behavior: 
- the breakpoint is not hit in the world.ts file.
- the corresponding breakpoint in dist/world.js hits

What is the expected behavior?
------------------------------
Debugging stops at the breakpoint in the typescript files.

Windows 10
VSCode 1.72.0
@oclif/core@1.16.5

**Comment by DaelDe** [comment]
I tested with an older project of mine and it works.
```
├── @oclif/command@1.8.0
├── @oclif/config@1.17.0
├── @oclif/dev-cli@1.26.0
├── @oclif/errors@1.3.4
├── @oclif/plugin-help@2.2.3
```

Could it somehow be related to the transition towards oclif/core only?

**Comment by mdonnalley** [comment]
@DaelDe You need to change the program from `"${workspaceFolder}\\bin\\run"` to `"${workspaceFolder}\\bin\\dev"` so that it runs on the typescript files. Otherwise, you would need to put your breakpoint in the compiled `dist/commands/hello/world.js`

**Comment by DaelDe** [comment]
Oh my, it is that easy. Maybe you can update the migration guide with this hint.

Thank you very much @mdonnalley

**Comment by calebAtIspot** [comment]
This is still a bug, the launch.json is broken for me using the starter template that calls `bin/dev`. Can we reopen this or do you want me to make a new issue @mdonnalley ?

```
/Users/calebatispot/.asdf/shims/node ./bin/dev hello world
(node:23743) [ERR_UNKNOWN_FILE_EXTENSION] Warning: TypeError
module: @oclif/core@4.0.3
task: findCommand (hello)
plugin: ocliftest
root: /Users/calebatispot/misc/candel/ocliftest
code: ERR_UNKNOWN_FILE_EXTENSION
message: Unknown file extension ".ts" for /Users/calebatispot/misc/candel/ocliftest/src/commands/hello/index.ts
See more details with DEBUG=*
(Use `node --trace-warnings ...` to show where the warning was created)
source-map-support.js:745
Warning: TypeError
    at Plugin.warn (/Users/calebatispot/misc/candel/ocliftest/node_modules/@oclif/core/lib/config/plugin.js:370:17)
    at /Users/calebatispot/misc/candel/ocliftest/node_modules/@oclif/core/lib/config/plugin.js:272:30
    at async Promise.all (index 0)
    at async Plugin._manifest (/Users/calebatispot/misc/candel/ocliftest/node_modules/@oclif/core/lib/config/plugin.js:253:24)
    at async Plugin.load (/Users/calebatispot/misc/candel/ocliftest/node_modules/@oclif/core/lib/config/plugin.js:204:25)
    at async PluginLoader.loadRoot (/Users/calebatispot/misc/candel/ocliftest/node_modules/@oclif/core/lib/config/plugin-loader.js:43:13)
    at async Config.load (/Users/calebatispot/misc/candel/ocliftest/node_modules/@oclif/core/lib/config/config.js:280:27)
    at async Function.load (/Users/calebatispot/misc/candel/ocliftest/node_modules/@oclif/core/lib/config/config.js:167:9)
    at async run (/Users/calebatispot/misc/candel/ocliftest/node_modules/@oclif/core/lib/main.js:61:20)
    at async file:///Users/calebatispot/misc/candel/ocliftest/bin/dev.js:6:1
config.js:59
module: @oclif/core@4.0.3
task: findCommand (hello)
plugin: ocliftest
root: /Users/calebatispot/misc/candel/ocliftest
code: ERR_UNKNOWN_FILE_EXTENSION
message: Unknown file extension ".ts" for /Users/calebatispot/misc/candel/ocliftest/src/commands/hello/index.ts
See more details with DEBUG=*
config.js:61
```

**Comment by calebAtIspot** [comment]
The starter template will work out of the box if `tsx` is used instead of `ts-node` and the following files are changed:

dev.ts <- note switched to .ts
```typescript
#!/usr/bin/env -S node --import tsx --no-warnings=ExperimentalWarning

// eslint-disable-next-line n/shebang
import {execute} from '@oclif/core'

await execute({development: true, dir: import.meta.url})
```

launch.json:
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Execute Command",
      "skipFiles": ["<node_internals>/**"],
      "type": "node",
      "request": "launch",
      "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/tsx",
      "args": ["bin/dev.ts", "hello", "world"],
    }
  ]
}

```

Relevant: https://stackoverflow.com/a/76343394/6629672

**Comment by mdonnalley** [comment]
@calebAtIspot I created a new issue: https://github.com/oclif/oclif/issues/1438
